# This file is meant for local development/testing and NOT meant for production!
# The backend and frontend is built on startup so first run may take some time

version: "3"
services:
  frontend:
    image: node:13-alpine
    ports:
      - "8888:3000"
    working_dir: /app/client
    networks:
      - default
      - private
    environment:
      NODE_PROXY_HOST: "backend"
    command: npm start
    volumes:
      - .:/app
  backend:
    image: gradle:jdk8
    working_dir: /home/gradle/project
    networks:
      - private
    volumes:
      - ".:/home/gradle/project"
      - "docker_certs:/certs"
    command: ./gradlew bootRun
    environment:
      DOCKER_HOST: "https://docker:2376"
      DOCKER_CERT_PATH: /certs
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_DATABASEPLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
  postgres:
    image: postgres
    restart: always
    networks:
      - private
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  docker:
    image: docker:stable-dind
    privileged: true
    restart: always
    environment:
      DOCKER_TLS_CERTDIR: certs
    networks:
      - private
    volumes:
      - docker_certs:/certs

volumes:
  docker_certs: {}

networks:
  private: {}
