#####################################################################################################
# This file only contains the default configuration!                                                #
# Environment-specific settings should be placed in a application-[dev|prod|test].yml file          #
# or by using OS environment variables. For more information on how to configure Spring see         #
# https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html #
#####################################################################################################

spring:
  profiles:
    # The application runs in dev mode by default! Override this in production mode!
    active: dev
  jpa:
    properties:
      hibernate:
        # Escape all table names to avoid issues with reserved keywords like "user"
        globally_quoted_identifiers: true

logging:
  level:
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
    # Hide log spam of docker pull progress
    com.spotify.docker.client.LoggingPullHandler: WARN


server:
  servlet:
    session:
      # Set server-side timeout of cookies
      # The client session-cookie will expire on browser close by default
      timeout: 24h

code-freak:
  instance: default
  docker:
    # All of the docker settings below will fall back to a system-depended default value if unset
    host: ~
    certPath: ~
    caCertPath: ~
    clientKeyPath: ~
    clientCertPath: ~
    # Define how (and if) images will be pulled on application startup
    pull-policy: never
    # Memory limit in bytes (2GiB)
    memory: 2147483648
    # Number of CPUs per container (0 means no limit)
    cpus: 0
    # Name of the network the container will be attached to
    network: bridge
  traefik:
    url: "http://localhost:8081"
  ide:
    # Interval for checking for idle containers in ms. Default 1 minute.
    idle-check-rate: 60000
    # Time span after which an idle container is shut down. Default 10 minutes.
    idle-shutdown-threshold: 600000
  frontend:
    # This can be used to inject custom javascript code (needs to include script tags).
    # It is injected after dependencies (like jQuery) and before template specific scripts.
    custom-script: ~
