title: Program in Java
description: Write a function `add(int a, int b)` that returns the sum of `a` and `b`
hidden:
  - src/test/**
  - .codeclimate.yml
protected:
  - build.gradle
  - settings.gradle
evaluation:
  - step: codeclimate
  - step: commandline
    options:
      image: gradle
      project-path: /home/gradle/project
      commands:
        - pwd
        - gradle test
        - ls build/test-results/test
  - step: junit
