name: CI

on: [push, pull_request, release]

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      # webpack build needs a lot of memory
      NODE_OPTIONS: --max_old_space_size=4096
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Assemble
        run: ./gradlew assemble -x bootJar

      - name: Check code
        run: ./gradlew check

      - name: Jib Docker Build
        run: ./gradlew jibDockerBuild -x check

      - name: Before cache
        run: |
          rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
          rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Before Deploy
        if: github.ref == 'ref/head/master' || startsWith(github.ref, 'ref/tags')
        run: |
          pip3 install --user --upgrade pip
          pip3 install --user docker-ci-deploy
          docker logout
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Deploy master branch as latest
        if: github.ref == 'ref/head/master'
        run: docker-ci-deploy --tag canary -- cfreak/codefreak

      - name: Deploy tags
        if: startsWith(github.ref, 'ref/tags')
        run: docker-ci-deploy --version-latest --version ${GITHUB_REF/refs\/tags\//} --version-semver cfreak/codefreak
